import{a as u,S as L,i as c}from"./assets/vendor-Do60_h77.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();u.defaults.baseURL="https://pixabay.com/api/";const b="10580483-492be0cc0cc7e2002da66cc4f",v=async(t,o)=>{const{data:a}=await u.get("",{params:{key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}});return a},m=document.querySelector(".gallery"),p=document.querySelector(".loader"),f=document.querySelector(".load-btn"),w=new L(".gallery a",{overlayOpacity:.9,animationSpeed:500});function S(t){const o=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:y,downloads:h})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img class="gallery-image" src="${a}" alt="${e}" />
          <div class="info-wrapper">
            <p class="tag-title">Likes <span class="tag-value">${r}</span></p>
            <p class="tag-title">Views <span class="tag-value">${n}</span></p>
            <p class="tag-title">Comments <span class="tag-value">${y}</span></p>
            <p class="tag-title">Downloads <span class="tag-value">${h}</span></p>
          </div>
        </a>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",o),w.refresh()}function q(){m.innerHTML=""}function $(){p.classList.remove("hidden")}function O(){p.classList.add("hidden")}function x(){f.classList.remove("hidden")}function l(){f.classList.add("hidden")}const B=document.querySelector(".form"),C=document.querySelector(".load-btn");let i=1,d="";const E=async t=>{i++,await g()};C.addEventListener("click",E);const P=async t=>{t.preventDefault(),d=t.target.elements["search-text"].value.trim(),d&&(i=1,l(),q(),await g(),t.target.reset())};B.addEventListener("submit",P);async function g(){$(),l();try{const{hits:t,totalHits:o}=await v(d,i);if(!t.length){c.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight",messageSize:"16px",messageColor:"white"});return}S(t,i);const a=document.querySelectorAll(".gallery-item"),s=a[a.length-t.length];s&&s.scrollIntoView({behavior:"smooth",block:"start"}),i*15>=o?(c.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"}),l()):x()}catch{c.error({message:"Something went wrong"})}finally{O()}}
//# sourceMappingURL=index.js.map
