import{a as u,S as L,i as l}from"./assets/vendor-Do60_h77.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();u.defaults.baseURL="https://pixabay.com/api/";const b="10580483-492be0cc0cc7e2002da66cc4f",w=async(t,a)=>{const{data:o}=await u.get("",{params:{key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}});return o},p=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-btn"),v=new L(".gallery a",{overlayOpacity:.9,animationSpeed:500});function S(t){const a=t.map(({webformatURL:o,largeImageURL:s,tags:e,likes:r,views:n,comments:y,downloads:h})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img class="gallery-image" src="${o}" alt="${e}" />
          <div class="info-wrapper">
            <p class="tag-title">Likes <span class="tag-value">${r}</span></p>
            <p class="tag-title">Views <span class="tag-value">${n}</span></p>
            <p class="tag-title">Comments <span class="tag-value">${y}</span></p>
            <p class="tag-title">Downloads <span class="tag-value">${h}</span></p>
          </div>
        </a>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",a),v.refresh()}function q(){p.innerHTML=""}function $(){m.classList.remove("hidden")}function O(){m.classList.add("hidden")}function x(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const B=document.querySelector(".form"),E=document.querySelector(".load-btn");let i=1,c="";const P=async t=>{i++,await g()};E.addEventListener("click",P);const C=async t=>{t.preventDefault(),c=t.target.elements["search-text"].value.trim(),c&&(i=1,q(),await g(),t.target.reset())};B.addEventListener("submit",C);async function g(){$();try{const{hits:t,totalHits:a}=await w(c,i);if(!t.length){l.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",position:"topRight",messageSize:"16px",messageColor:"white"}),d();return}S(t,i);const o=document.querySelectorAll(".gallery-item"),s=o[o.length-t.length];s&&s.scrollIntoView({behavior:"smooth",block:"start"}),i*15>=a?d():x()}catch{l.error({message:"Something went wrong"})}finally{O()}}
//# sourceMappingURL=index.js.map
